apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: marketplace-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: marketplace-service
  minReplicas: 1
  maxReplicas: 3
